### ISSUE TITLE
Correct Icon for Repository in Footer

### ISSUE THREAD

**Issue by nickbabcock** [UM-ESG/ESG-Website#101]
Currently the footer contains a wrench icon that links to the repo. The icon shouldn't be a wrench, but Github's octicon. See the following for possible sources:

http://fortawesome.github.io/Font-Awesome/icon/github/
https://octicons.github.com/icon/mark-github/

/cc @nealrp

**Comment by nealrp** [comment]
Thanks Nick. It will be corrected shortly.
